# Generated by Django 3.0.4 on 2020-05-16 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_restaurantprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RestaurantProfile',
        ),
    ]
