# Generated by Django 3.0.4 on 2020-05-18 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='item',
            field=models.ManyToManyField(blank=True, to='store.MenuItems'),
        ),
        migrations.AlterField(
            model_name='order',
            name='item',
            field=models.ManyToManyField(blank=True, to='store.MenuItems'),
        ),
    ]
